name: Deploy or Manage SQL Server Container

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: google-github-actions/setup-gcloud@v2

      - name: Sanity: confirm bash + principal
        run: |
          echo "SHELL=$SHELL"
          bash --version | head -n1
          gcloud auth list
          gcloud config set project "${{ secrets.GCP_PROJECT_ID }}"
          gcloud config set compute/zone "us-central1-a"

      - name: Copy provision script
        run: |
          gcloud -q compute scp \
            --tunnel-through-iap \
            --zone "us-central1-a" \
            scripts/provision_sql.sh \
            "sql-linux-vm:/tmp/provision_sql.sh"

      - name: Run provision script
        env:
          SA_PWD: ${{ secrets.SQL_SA_PASSWORD }}
          CI_LOGIN: ci_user
          CI_PASSWORD: ${{ secrets.SQL_CI_PASSWORD }}
          DATA_DIR: /mnt/sqldata
          DB_NAME: DemoDB
        run: |
          # Create wrapper script to avoid quoting issues
          cat > /tmp/run-provision.sh << 'WRAPPER_EOF'
          #!/bin/bash
          chmod +x /tmp/provision_sql.sh
          SA_PWD="$1" CI_LOGIN="$2" CI_PASSWORD="$3" DATA_DIR="$4" DB_NAME="$5" sudo -E /tmp/provision_sql.sh
          WRAPPER_EOF
          
          # Copy wrapper to VM
          gcloud -q compute scp /tmp/run-provision.sh sql-linux-vm:/tmp/run-provision.sh \
            --tunnel-through-iap \
            --zone "us-central1-a"
          
          # Execute wrapper with arguments
          gcloud -q compute ssh "sql-linux-vm" \
            --tunnel-through-iap \
            --zone "us-central1-a" \
            --strict-host-key-checking=no \
            --command="bash /tmp/run-provision.sh '$SA_PWD' '$CI_LOGIN' '$CI_PASSWORD' '$DATA_DIR' '$DB_NAME'"

      - name: Inspect container (on failure)
        if: failure()
        run: |
          gcloud -q compute ssh "sql-linux-vm" \
            --tunnel-through-iap \
            --zone "us-central1-a" \
            --strict-host-key-checking=no \
            --command='sudo docker ps -a; echo "---- logs ----"; sudo docker logs --tail=200 mssql || true; echo "---- dir ----"; sudo ls -l /mnt/sqldata'
