name: Deploy SQL Server to GCP

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        type: choice
        options:
          - deploy
          - restart
          - stop
        default: 'deploy'
  push:
    branches:
      - main
    paths:
      - 'infra/scripts/init-database.sql'
      - '.github/workflows/deploy-sql.yml'

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_ZONE: us-central1-a
  VM_NAME: sql-linux-vm
  CONTAINER_NAME: mssql
  SQL_VERSION: "2022-latest"
  CLOUDSDK_CORE_DISABLE_PROMPTS: "1"  # Auto-answer yes to all prompts

jobs:
  deploy-sql-server:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure gcloud
        run: |
          gcloud config set project "$GCP_PROJECT_ID"
          gcloud config set compute/zone "$GCP_ZONE"
          
          echo "=== Authenticated as: ==="
          gcloud auth list
          
          echo ""
          echo "=== VM Status: ==="
          gcloud compute instances describe $VM_NAME --format="value(status,metadata.items[key='enable-oslogin'].value)"

      - name: Test SSH Connection
        run: |
          echo "=== Testing IAP SSH Connection ==="
          gcloud compute ssh $VM_NAME \
            --tunnel-through-iap \
            --command "echo 'SSH connection successful!'"

      - name: Deploy or Manage SQL Server Container
        env:
          SA_PASSWORD: ${{ secrets.SQL_SA_PASSWORD }}
          CI_PASSWORD: ${{ secrets.SQL_CI_PASSWORD }}
          ACTION: ${{ github.event.inputs.action || 'deploy' }}
        run: |
          echo "=== Action: $ACTION ==="
          
          if [ "$ACTION" = "stop" ]; then
            echo "Stopping SQL Server container..."
            gcloud compute ssh $VM_NAME --tunnel-through-iap \
              --command "sudo docker stop $CONTAINER_NAME || true"
            exit 0
          fi
          
          if [ "$ACTION" = "restart" ]; then
            echo "Restarting SQL Server container..."
            gcloud compute ssh $VM_NAME --tunnel-through-iap \
              --command "sudo docker restart $CONTAINER_NAME"
            exit 0
          fi
          
          # Deploy action
          echo "=== Deploying SQL Server 2022 ==="
          
          # Pull latest image
          echo "Pulling SQL Server image..."
          gcloud compute ssh $VM_NAME --tunnel-through-iap \
            --command "sudo docker pull mcr.microsoft.com/mssql/server:$SQL_VERSION"
          
          # Ensure correct permissions on persistent volume (idempotent)
          echo "Setting correct permissions on /mnt/sqldata..."
          gcloud compute ssh $VM_NAME --tunnel-through-iap \
            --command "sudo chown -R 10001:0 /mnt/sqldata && sudo chmod -R 770 /mnt/sqldata"
          
          # Stop and remove existing container if present
          echo "Removing existing container if present..."
          gcloud compute ssh $VM_NAME --tunnel-through-iap \
            --command "sudo docker rm -f $CONTAINER_NAME 2>/dev/null || true"
          
          # Deploy SQL Server container with persistent storage
          echo "Starting new SQL Server container..."
          gcloud compute ssh $VM_NAME --tunnel-through-iap \
            --command "sudo docker run -d \
              --name $CONTAINER_NAME \
              --hostname sqlserver \
              --restart unless-stopped \
              -e ACCEPT_EULA=Y \
              -e MSSQL_PID=Developer \
              -e 'MSSQL_SA_PASSWORD=$SA_PASSWORD' \
              -p 1433:1433 \
              -v /mnt/sqldata:/var/opt/mssql \
              mcr.microsoft.com/mssql/server:$SQL_VERSION"
          
          # Wait for SQL Server to be ready (up to 5 minutes)
          echo "Waiting for SQL Server to become healthy (max 5 minutes)..."
          for i in $(seq 1 60); do
            # Check container health status first
            STATUS=\$(gcloud compute ssh $VM_NAME --tunnel-through-iap \
              --command "sudo docker inspect -f '{{.State.Health.Status}}' $CONTAINER_NAME 2>/dev/null || echo 'unknown'")
            
            if [ "\$STATUS" = "healthy" ]; then
              echo "✅ SQL Server is healthy!"
              break
            fi
            
            # Fallback: try simple query
            if gcloud compute ssh $VM_NAME --tunnel-through-iap \
              --command "sudo docker exec $CONTAINER_NAME /opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P '$SA_PASSWORD' -C -Q 'SELECT 1' >/dev/null 2>&1"; then
              echo "✅ SQL Server is responding!"
              break
            fi
            
            if [ \$i -eq 60 ]; then
              echo "❌ SQL Server not healthy after 5 minutes. Last logs:"
              gcloud compute ssh $VM_NAME --tunnel-through-iap \
                --command "sudo docker logs --tail=200 $CONTAINER_NAME" || true
              exit 1
            fi
            
            echo "Waiting... (\$i/60)"
            sleep 5
          done
          
          # Copy init script to VM
          echo "=== Copying initialization script ==="
          gcloud compute scp infra/scripts/init-database.sql $VM_NAME:/tmp/init-database.sql \
            --tunnel-through-iap
          
          # Run init script with variable substitution
          echo "=== Running database initialization (idempotent) ==="
          gcloud compute ssh $VM_NAME --tunnel-through-iap \
            --command "sudo docker exec -i $CONTAINER_NAME /opt/mssql-tools18/bin/sqlcmd \
              -S localhost -U SA -P '$SA_PASSWORD' -C -b \
              -v CI_PASSWORD='$CI_PASSWORD' \
              -v VERSION='\$(date +%Y%m%d-%H%M%S)' \
              -i /tmp/init-database.sql"
          
          # Verify deployment
          echo "=== Verifying deployment ==="
          gcloud compute ssh $VM_NAME --tunnel-through-iap \
            --command "sudo docker exec $CONTAINER_NAME /opt/mssql-tools18/bin/sqlcmd \
              -S localhost -U SA -P '$SA_PASSWORD' -C \
              -Q 'SELECT name, database_id, create_date FROM sys.databases WHERE name = N''DemoDB''; SELECT name, type_desc FROM sys.database_principals WHERE name = N''ci_user'';'"
          
          echo ""
          echo "=== ✅ Deployment complete! ==="
          echo "SQL Server 2022 is running on VM: $VM_NAME"
          echo "Connect via: 34.57.37.222,1433"
          echo "Database: DemoDB"
          echo "User: ci_user"
          echo "Container status: \$(gcloud compute ssh $VM_NAME --tunnel-through-iap --command 'sudo docker ps --filter name=$CONTAINER_NAME --format \"{{.Status}}\"')"

      - name: Clean up
        if: always()
        run: |
          gcloud compute ssh $VM_NAME --tunnel-through-iap \
            --command "rm -f /tmp/init-database.sql" || true
